name: deploy pages
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: wasm -> target
      - name: install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: build wasm
        run: ./scripts/build-wasm.sh

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
        env:
          HUSKY: 0
      - run: yarn build

      - uses: actions/configure-pages@v5

      - name: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build
      - name: deploy
        uses: actions/deploy-pages@v4
