name: Build and deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.3
          # The cache folder will be placed in the build directory,
          #  so make sure it doesn't conflict with anything!
          actions-cache-folder: 'emsdk-cache'
      - name: Verify emsdk
        run: emcc -v
      - name: Build WASM
        run: ./scripts/build/wasm.sh

      # https://stackoverflow.com/a/62244232
      # https://dev.to/mpocock1/how-to-cache-nodemodules-in-github-actions-with-yarn-24eh
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('/yarn.lock') }}

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install --frozen-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - name: Build web
        run: |
          yarn build

          cd build
          touch .nojekyll

          cd dist/wasm
          rm *.{sh,cpp}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: build
          single-commit: true
